### ISSUE TITLE
Put favorite streams on top

### ISSUE THREAD

**Issue by Dune-jr** [Kunamatata/Starcraft2ChromeExtension#10]
Sweet, an alert about that nice guy, he's begun streaming!
_*clicks extension icon*_
_*scroll down*_
_*scrolls up slower*_
Ah, here it is, with 1 viewer
_*clicks*_

How about listing the starred streams first? :rabbit:

**Comment by triartleet** [comment]
Hi again. Could I have it? xD

**Comment by Kunamatata** [comment]
Hey @fllprbt great job ! Thanks for all your help :) 👻 🎃 It's working and awesome !

**Comment by Kunamatata** [comment]
@jordy-ruiz thanks to @fllprbt this is now working ! I'll be putting it live on the store soon :)
