### ISSUE TITLE
Fix Lodash package vulnerability inside package-lock.json

### ISSUE THREAD

**Issue by Kunamatata** [Kunamatata/Starcraft2ChromeExtension#15]
Upgrade Lodash dependency from:
`"lodash": "4.17.4"` to `"lodash": "4.17.5"`

**Comment by triartleet** [comment]
Can I have this?

**Comment by Kunamatata** [comment]
Feel free to do so @fllprbt 😄

**Comment by triartleet** [comment]
I got everything off for Lodash using version 4.17.4 except 1 weak vulnerability :

https://www.npmjs.com/advisories/577

To be able to fix this I need to install grunt 4.0 (but I am having a warning from npm that it will break the project, wanna check this out as well)?

**Comment by Kunamatata** [comment]
@fllprbt As a little help, you can open package-lock.json and change every occurence of `"lodash": "4.17.4"` to `"lodash": "4.17.5"` instead of installing new things ;) Since it's a minor version, it won't break anything.
Hope this little tip helps !

**Comment by triartleet** [comment]
Erm... package-lock.json should not be edited. Maybe you mix it with package.json? Lodash btw is installed as a babel dependency in your project. So in order to change that, I have to go all the way back.

**Comment by Kunamatata** [comment]
@fllprbt Sorry my bad! You are right. Even when trying with all latest DevDependencies, it seems like it's still using lodash 4.17.4

**Comment by triartleet** [comment]
I think you will be ok with gulp4.0, ill submit the PR in a few minutes so you could test and tell me.

**Comment by Kunamatata** [comment]
@fllprbt The latest version of gulp is 3.9.1 https://www.npmjs.com/package/gulp 

**EDIT:** Nevermind I didn't know gulp 4 was out.

**Comment by triartleet** [comment]
Oh there are merge conflicts in my updated gulpfile, could you integrate them, and also change the deployment command from `npm install -g gulp` to `npm install -g gulp@^4.0`

**Comment by fllprbt** [comment]
Oh there are merge conflicts in my updated gulpfile, could you integrate them, do the edit I mentioned about the global gulp version and report? Thanks.

**Comment by triartleet** [comment]
Travis build is successful, I think you are good to go :) https://github.com/Kunamatata/Starcraft2ChromeExtension/pull/23

**Comment by Kunamatata** [comment]
Thanks @fllprbt ! Good work :smile: Happy Hacktoberfest 👻 🎃
