### ISSUE TITLE
Fix weird padding on the right side of #container-extension

### ISSUE THREAD

**Issue by Kunamatata** [Kunamatata/Starcraft2ChromeExtension#16]
The fix is easy, open the following file : `style.css`
In the #container-extension id style **change** `width` to `min-width`
![image](https://user-images.githubusercontent.com/2602652/46397104-2dcbc580-c6a6-11e8-92c7-055a8a6b682a.png)

**Comment by thomas0306** [comment]
Hi, can I help for this issue?

**Comment by Kunamatata** [comment]
Hi @thomas0306 feel free to help :smile:

**Comment by morgsmccauley** [comment]
Raised #17 for this! Sorry @Kunamatata, forgot to mention I picked this up!
