### ISSUE TITLE
Can we identify stream names containing "toss" as protoss?

### ISSUE THREAD

**Issue by Dune-jr** [Kunamatata/Starcraft2ChromeExtension#5]
There's a bunch of these streams every day:

![image](http://puu.sh/oRDEv/e84dfbc9e0.png)

I can't think of english words used in titles containing the "toss"... maybe it's better to match to " toss"||"toss " if there's any.

**Comment by Kunamatata** [comment]
The api call filters with streams having starcraft 2 selected. That guy probably has starcraft 2 selected as a title to stream and didn't switch it out for the other game.

**Comment by Dune-jr** [comment]
Ah, sorry for the misunderstanding. I was not talking about the first streamer, but the last two. Protoss players often write "toss" instead of protoss in their stream title.

![image](http://puu.sh/oS7iw/9730eace3b.png)
![image2](http://puu.sh/oS7l2/9fe2a1a7c4.png)

**Comment by Kunamatata** [comment]
Oh ok @Dunedune ! We most certainly can do this! Let's make this happen! I've been working on having a proper build process for the chrome extension. I'll be pushing it soon to master :D

**Comment by Kunamatata** [comment]
Pushed this to dev branch: 
`stream.channel.status.match(/protoss/i) || stream.channel.status.match(/toss/i)`
Not sure if it's what we want. Might want to remove the first one since the second matches the first
Let me know what you think @Dunedune

**Comment by Dune-jr** [comment]
I would rather go with 

`stream.channel.status.match(/protoss/i) || stream.channel.status.match(/(^|\W)toss($|\W)/i)`

For regexp testing: https://regex101.com/r/pS6vH1/31

You wouldn't want to tag that guy as protoss:
![Image](http://puu.sh/p0Qgd/b7fd50d1d4.png)

**Comment by Kunamatata** [comment]
Much better :D 

P.S : What are you using to test? @Dunedune

**Comment by Dune-jr** [comment]
Nothing really, I just open the popup.html.

**Comment by Dune-jr** [comment]
Fixed by 747ac43ee0fafbe58f6e04e5f1bc3fb30b913fed
