### ISSUE TITLE
Shouldn't the grey viewer count icon be... grey?

### ISSUE THREAD

**Issue by Dune-jr** [Kunamatata/Starcraft2ChromeExtension#6]
It's black atm (0/0/0/255)
Shouldn't it rather be grey, like the comment says?

The idea would be to not stand out too much from the default grey chrome background: ![image](http://puu.sh/oRZNR/da9f88610c.jpg) when there is no event
By the way, is there a reason why the icon is not transparent? :x

**Comment by Kunamatata** [comment]
It should be grey indeed, just forgot to change it back to grey after testing black. Also the extension icon isn't the correct one. I had one which was nice but for some reason it disappeared I'll fix that!
♥

**Comment by Kunamatata** [comment]
This has been solved in the lastest version @Dunedune
