### ISSUE TITLE
Streams may be tagged with several icons

### ISSUE THREAD

**Issue by Dune-jr** [Kunamatata/Starcraft2ChromeExtension#8]
Here's what PengWin's stream looks like:

![Image](http://puu.sh/p07s9/dee5db240a.jpg)

But in the end, it doesn't look too bad. Maybe we should keep it! :)

**Comment by Kunamatata** [comment]
That's kind of hilarious. I'm trying to figure a way for that not to happen. Maybe stop at the first word that is found? Not sure. Should we leave it like that for now?

**Comment by Dune-jr** [comment]
That doesn't look too bad. Bugs are features!

**Comment by Kunamatata** [comment]
If we get more feedback from users we can decide !
