### ISSUE TITLE
Improve readability by displaying viewers count on the same line as the title

### ISSUE THREAD

**Issue by Dune-jr** [Kunamatata/Starcraft2ChromeExtension#9]
A very quick mockup:

![Image](http://puu.sh/p07r8/7dc82e55ae.png)
What are you first impressions?

We could also display the viewers count using Twitch's icon: 
![Image](http://puu.sh/p07OX/dd8be74820.png)

**Comment by Kunamatata** [comment]
I like that better than the current! Let's make that happen =D
